name: Update Data and Deploy Dashboard

on:
  schedule:
    # Run the workflow on the 1st of every month at 12:00 UTC
    - cron: "0 12 1 * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Ensure this matches your local Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the data update script
    - name: Update data
      run: |
        python data_setup.py

    # Optional: Streamlit Deployment (if you're using Streamlit Cloud)
    - name: Deploy dashboard
      run: |
        streamlit run dashboard.py --server.port 8501
      env:
        STREAMLIT_SERVER_PORT: ${{ secrets.STREAMLIT_PORT }}
        STREAMLIT_CLOUD_DEPLOY_TOKEN: ${{ secrets.STREAMLIT_CLOUD_DEPLOY_TOKEN }}
